spring:
  datasource:
    url: jdbc:h2:file:./data/worktrack-db-clean;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      connection-test-query: SELECT 1
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    restart:
      enabled=true:

user:
  service:
    base-url: http://localhost:8000